/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPendingApprovalsRouteImport } from './routes/dashboard/pending-approvals'
import { Route as DashboardMyExpensesRouteImport } from './routes/dashboard/my-expenses'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardSettingsVendorsRouteImport } from './routes/dashboard/settings/vendors'
import { Route as DashboardSettingsVendorBillsRouteImport } from './routes/dashboard/settings/vendor-bills'
import { Route as DashboardSettingsSalesOrdersRouteImport } from './routes/dashboard/settings/sales-orders'
import { Route as DashboardSettingsPurchaseOrdersRouteImport } from './routes/dashboard/settings/purchase-orders'
import { Route as DashboardSettingsCustomerInvoicesRouteImport } from './routes/dashboard/settings/customer-invoices'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminCustomersRouteImport } from './routes/dashboard/admin/customers'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPendingApprovalsRoute =
  DashboardPendingApprovalsRouteImport.update({
    id: '/pending-approvals',
    path: '/pending-approvals',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMyExpensesRoute = DashboardMyExpensesRouteImport.update({
  id: '/my-expenses',
  path: '/my-expenses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsVendorsRoute =
  DashboardSettingsVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsVendorBillsRoute =
  DashboardSettingsVendorBillsRouteImport.update({
    id: '/vendor-bills',
    path: '/vendor-bills',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsSalesOrdersRoute =
  DashboardSettingsSalesOrdersRouteImport.update({
    id: '/sales-orders',
    path: '/sales-orders',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsPurchaseOrdersRoute =
  DashboardSettingsPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsCustomerInvoicesRoute =
  DashboardSettingsCustomerInvoicesRouteImport.update({
    id: '/customer-invoices',
    path: '/customer-invoices',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminCustomersRoute = DashboardAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/my-expenses': typeof DashboardMyExpensesRoute
  '/dashboard/pending-approvals': typeof DashboardPendingApprovalsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/customers': typeof DashboardAdminCustomersRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/settings/customer-invoices': typeof DashboardSettingsCustomerInvoicesRoute
  '/dashboard/settings/purchase-orders': typeof DashboardSettingsPurchaseOrdersRoute
  '/dashboard/settings/sales-orders': typeof DashboardSettingsSalesOrdersRoute
  '/dashboard/settings/vendor-bills': typeof DashboardSettingsVendorBillsRoute
  '/dashboard/settings/vendors': typeof DashboardSettingsVendorsRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/my-expenses': typeof DashboardMyExpensesRoute
  '/dashboard/pending-approvals': typeof DashboardPendingApprovalsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/customers': typeof DashboardAdminCustomersRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/settings/customer-invoices': typeof DashboardSettingsCustomerInvoicesRoute
  '/dashboard/settings/purchase-orders': typeof DashboardSettingsPurchaseOrdersRoute
  '/dashboard/settings/sales-orders': typeof DashboardSettingsSalesOrdersRoute
  '/dashboard/settings/vendor-bills': typeof DashboardSettingsVendorBillsRoute
  '/dashboard/settings/vendors': typeof DashboardSettingsVendorsRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/my-expenses': typeof DashboardMyExpensesRoute
  '/dashboard/pending-approvals': typeof DashboardPendingApprovalsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/customers': typeof DashboardAdminCustomersRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/settings/customer-invoices': typeof DashboardSettingsCustomerInvoicesRoute
  '/dashboard/settings/purchase-orders': typeof DashboardSettingsPurchaseOrdersRoute
  '/dashboard/settings/sales-orders': typeof DashboardSettingsSalesOrdersRoute
  '/dashboard/settings/vendor-bills': typeof DashboardSettingsVendorBillsRoute
  '/dashboard/settings/vendors': typeof DashboardSettingsVendorsRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/my-expenses'
    | '/dashboard/pending-approvals'
    | '/dashboard/'
    | '/dashboard/admin/customers'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$projectId'
    | '/dashboard/settings/customer-invoices'
    | '/dashboard/settings/purchase-orders'
    | '/dashboard/settings/sales-orders'
    | '/dashboard/settings/vendor-bills'
    | '/dashboard/settings/vendors'
    | '/dashboard/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/my-expenses'
    | '/dashboard/pending-approvals'
    | '/dashboard'
    | '/dashboard/admin/customers'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$projectId'
    | '/dashboard/settings/customer-invoices'
    | '/dashboard/settings/purchase-orders'
    | '/dashboard/settings/sales-orders'
    | '/dashboard/settings/vendor-bills'
    | '/dashboard/settings/vendors'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/my-expenses'
    | '/dashboard/pending-approvals'
    | '/dashboard/'
    | '/dashboard/admin/customers'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$projectId'
    | '/dashboard/settings/customer-invoices'
    | '/dashboard/settings/purchase-orders'
    | '/dashboard/settings/sales-orders'
    | '/dashboard/settings/vendor-bills'
    | '/dashboard/settings/vendors'
    | '/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pending-approvals': {
      id: '/dashboard/pending-approvals'
      path: '/pending-approvals'
      fullPath: '/dashboard/pending-approvals'
      preLoaderRoute: typeof DashboardPendingApprovalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/my-expenses': {
      id: '/dashboard/my-expenses'
      path: '/my-expenses'
      fullPath: '/dashboard/my-expenses'
      preLoaderRoute: typeof DashboardMyExpensesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/vendors': {
      id: '/dashboard/settings/vendors'
      path: '/vendors'
      fullPath: '/dashboard/settings/vendors'
      preLoaderRoute: typeof DashboardSettingsVendorsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/vendor-bills': {
      id: '/dashboard/settings/vendor-bills'
      path: '/vendor-bills'
      fullPath: '/dashboard/settings/vendor-bills'
      preLoaderRoute: typeof DashboardSettingsVendorBillsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/sales-orders': {
      id: '/dashboard/settings/sales-orders'
      path: '/sales-orders'
      fullPath: '/dashboard/settings/sales-orders'
      preLoaderRoute: typeof DashboardSettingsSalesOrdersRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/purchase-orders': {
      id: '/dashboard/settings/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/dashboard/settings/purchase-orders'
      preLoaderRoute: typeof DashboardSettingsPurchaseOrdersRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/customer-invoices': {
      id: '/dashboard/settings/customer-invoices'
      path: '/customer-invoices'
      fullPath: '/dashboard/settings/customer-invoices'
      preLoaderRoute: typeof DashboardSettingsCustomerInvoicesRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/customers': {
      id: '/dashboard/admin/customers'
      path: '/customers'
      fullPath: '/dashboard/admin/customers'
      preLoaderRoute: typeof DashboardAdminCustomersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface DashboardAdminRouteRouteChildren {
  DashboardAdminCustomersRoute: typeof DashboardAdminCustomersRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminCustomersRoute: DashboardAdminCustomersRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsCustomerInvoicesRoute: typeof DashboardSettingsCustomerInvoicesRoute
  DashboardSettingsPurchaseOrdersRoute: typeof DashboardSettingsPurchaseOrdersRoute
  DashboardSettingsSalesOrdersRoute: typeof DashboardSettingsSalesOrdersRoute
  DashboardSettingsVendorBillsRoute: typeof DashboardSettingsVendorBillsRoute
  DashboardSettingsVendorsRoute: typeof DashboardSettingsVendorsRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsCustomerInvoicesRoute:
      DashboardSettingsCustomerInvoicesRoute,
    DashboardSettingsPurchaseOrdersRoute: DashboardSettingsPurchaseOrdersRoute,
    DashboardSettingsSalesOrdersRoute: DashboardSettingsSalesOrdersRoute,
    DashboardSettingsVendorBillsRoute: DashboardSettingsVendorBillsRoute,
    DashboardSettingsVendorsRoute: DashboardSettingsVendorsRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardMyExpensesRoute: typeof DashboardMyExpensesRoute
  DashboardPendingApprovalsRoute: typeof DashboardPendingApprovalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardMyExpensesRoute: DashboardMyExpensesRoute,
  DashboardPendingApprovalsRoute: DashboardPendingApprovalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
